### ISSUE TITLE
Đặc tả phần mềm bằng use case

### ISSUE THREAD

**Issue by DucManh1402** [DucManh1402/SupportPregnantWomen#13]
Use Case

**Comment by nguyenminhthuan2309** [comment]
https://github.com/DucManh1402/SupportPregnantWomen/blob/master/%C4%90%E1%BA%B7c%20t%E1%BA%A3%20ph%E1%BA%A7n%20m%E1%BB%81m%20b%E1%BA%B1ng%20Usecase.pdf
